package cr.ac.una.sigeceunasecurityws.controller;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.2
 * 2024-10-31T16:00:38.428-06:00
 * Generated source version: 4.0.2
 *
 */
@WebService(targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", name = "RoleController")
@XmlSeeAlso({ObjectFactory.class})
public interface RoleController {

    @WebMethod
    @Action(input = "http://controller.sigeceunasecurityws.una.ac.cr/RoleController/getRoleByIDRequest", output = "http://controller.sigeceunasecurityws.una.ac.cr/RoleController/getRoleByIDResponse")
    @RequestWrapper(localName = "getRoleByID", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.GetRoleByID")
    @ResponseWrapper(localName = "getRoleByIDResponse", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.GetRoleByIDResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.sigeceunasecurityws.controller.RoleDto getRoleByID(

        @WebParam(name = "ID", targetNamespace = "")
        java.lang.Long id
    );

    @WebMethod
    @Action(input = "http://controller.sigeceunasecurityws.una.ac.cr/RoleController/getRolesOfSystemRequest", output = "http://controller.sigeceunasecurityws.una.ac.cr/RoleController/getRolesOfSystemResponse")
    @RequestWrapper(localName = "getRolesOfSystem", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.GetRolesOfSystem")
    @ResponseWrapper(localName = "getRolesOfSystemResponse", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.GetRolesOfSystemResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<cr.ac.una.sigeceunasecurityws.controller.RoleDto> getRolesOfSystem(

        @WebParam(name = "systemDto", targetNamespace = "")
        cr.ac.una.sigeceunasecurityws.controller.SystemsDto systemDto
    );

    @WebMethod
    @Action(input = "http://controller.sigeceunasecurityws.una.ac.cr/RoleController/deleteRoleByIDRequest", output = "http://controller.sigeceunasecurityws.una.ac.cr/RoleController/deleteRoleByIDResponse")
    @RequestWrapper(localName = "deleteRoleByID", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.DeleteRoleByID")
    @ResponseWrapper(localName = "deleteRoleByIDResponse", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.DeleteRoleByIDResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean deleteRoleByID(

        @WebParam(name = "RoleIDToDelete", targetNamespace = "")
        java.lang.Long roleIDToDelete
    );

    @WebMethod
    @Action(input = "http://controller.sigeceunasecurityws.una.ac.cr/RoleController/saveRoleRequest", output = "http://controller.sigeceunasecurityws.una.ac.cr/RoleController/saveRoleResponse")
    @RequestWrapper(localName = "saveRole", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.SaveRole")
    @ResponseWrapper(localName = "saveRoleResponse", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.SaveRoleResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.sigeceunasecurityws.controller.RoleDto saveRole(

        @WebParam(name = "RoleToSave", targetNamespace = "")
        cr.ac.una.sigeceunasecurityws.controller.RoleDto roleToSave
    );

    @WebMethod
    @Action(input = "http://controller.sigeceunasecurityws.una.ac.cr/RoleController/getRolesRequest", output = "http://controller.sigeceunasecurityws.una.ac.cr/RoleController/getRolesResponse")
    @RequestWrapper(localName = "getRoles", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.GetRoles")
    @ResponseWrapper(localName = "getRolesResponse", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.GetRolesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<cr.ac.una.sigeceunasecurityws.controller.RoleDto> getRoles()
;
}
