package cr.ac.una.sigeceunasecurityws.controller;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.2
 * 2024-10-31T16:00:38.840-06:00
 * Generated source version: 4.0.2
 *
 */
@WebService(targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", name = "SystemsController")
@XmlSeeAlso({ObjectFactory.class})
public interface SystemsController {

    @WebMethod
    @Action(input = "http://controller.sigeceunasecurityws.una.ac.cr/SystemsController/getSystemsByIDRequest", output = "http://controller.sigeceunasecurityws.una.ac.cr/SystemsController/getSystemsByIDResponse")
    @RequestWrapper(localName = "getSystemsByID", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.GetSystemsByID")
    @ResponseWrapper(localName = "getSystemsByIDResponse", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.GetSystemsByIDResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.sigeceunasecurityws.controller.SystemsDto getSystemsByID(

        @WebParam(name = "ID", targetNamespace = "")
        java.lang.Long id
    );

    @WebMethod
    @Action(input = "http://controller.sigeceunasecurityws.una.ac.cr/SystemsController/getSystemsRequest", output = "http://controller.sigeceunasecurityws.una.ac.cr/SystemsController/getSystemsResponse")
    @RequestWrapper(localName = "getSystems", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.GetSystems")
    @ResponseWrapper(localName = "getSystemsResponse", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.GetSystemsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<cr.ac.una.sigeceunasecurityws.controller.SystemsDto> getSystems()
;

    @WebMethod
    @Action(input = "http://controller.sigeceunasecurityws.una.ac.cr/SystemsController/saveSystemRequest", output = "http://controller.sigeceunasecurityws.una.ac.cr/SystemsController/saveSystemResponse")
    @RequestWrapper(localName = "saveSystem", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.SaveSystem")
    @ResponseWrapper(localName = "saveSystemResponse", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.SaveSystemResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.sigeceunasecurityws.controller.SystemsDto saveSystem(

        @WebParam(name = "SystemToRegister", targetNamespace = "")
        cr.ac.una.sigeceunasecurityws.controller.SystemsDto systemToRegister
    );

    @WebMethod
    @Action(input = "http://controller.sigeceunasecurityws.una.ac.cr/SystemsController/getSystemByIdRequest", output = "http://controller.sigeceunasecurityws.una.ac.cr/SystemsController/getSystemByIdResponse")
    @RequestWrapper(localName = "getSystemById", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.GetSystemById")
    @ResponseWrapper(localName = "getSystemByIdResponse", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.GetSystemByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.sigeceunasecurityws.controller.Response getSystemById(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebMethod
    @Action(input = "http://controller.sigeceunasecurityws.una.ac.cr/SystemsController/deleteSystemByIDRequest", output = "http://controller.sigeceunasecurityws.una.ac.cr/SystemsController/deleteSystemByIDResponse")
    @RequestWrapper(localName = "deleteSystemByID", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.DeleteSystemByID")
    @ResponseWrapper(localName = "deleteSystemByIDResponse", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.DeleteSystemByIDResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean deleteSystemByID(

        @WebParam(name = "SystemIDToDelete", targetNamespace = "")
        java.lang.Long systemIDToDelete
    );
}
