package cr.ac.una.sigeceunasecurityws.controller;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.2
 * 2024-10-31T16:00:37.930-06:00
 * Generated source version: 4.0.2
 *
 */
@WebService(targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", name = "UserController")
@XmlSeeAlso({ObjectFactory.class})
public interface UserController {

    @WebMethod
    @Action(input = "http://controller.sigeceunasecurityws.una.ac.cr/UserController/validateUserWithTempPasswordRsRequest", output = "http://controller.sigeceunasecurityws.una.ac.cr/UserController/validateUserWithTempPasswordRsResponse")
    @RequestWrapper(localName = "validateUserWithTempPasswordRs", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.ValidateUserWithTempPasswordRs")
    @ResponseWrapper(localName = "validateUserWithTempPasswordRsResponse", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.ValidateUserWithTempPasswordRsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.sigeceunasecurityws.controller.Response validateUserWithTempPasswordRs(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://controller.sigeceunasecurityws.una.ac.cr/UserController/validateUserRequest", output = "http://controller.sigeceunasecurityws.una.ac.cr/UserController/validateUserResponse")
    @RequestWrapper(localName = "validateUser", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.ValidateUser")
    @ResponseWrapper(localName = "validateUserResponse", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.ValidateUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.sigeceunasecurityws.controller.UserDto validateUser(

        @WebParam(name = "identification", targetNamespace = "")
        java.lang.String identification,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    );

    @WebMethod
    @Action(input = "http://controller.sigeceunasecurityws.una.ac.cr/UserController/getUserByIDRequest", output = "http://controller.sigeceunasecurityws.una.ac.cr/UserController/getUserByIDResponse")
    @RequestWrapper(localName = "getUserByID", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.GetUserByID")
    @ResponseWrapper(localName = "getUserByIDResponse", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.GetUserByIDResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.sigeceunasecurityws.controller.UserDto getUserByID(

        @WebParam(name = "ID", targetNamespace = "")
        java.lang.Long id
    );

    @WebMethod
    @Action(input = "http://controller.sigeceunasecurityws.una.ac.cr/UserController/isUserWithEmailRequest", output = "http://controller.sigeceunasecurityws.una.ac.cr/UserController/isUserWithEmailResponse")
    @RequestWrapper(localName = "isUserWithEmail", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.IsUserWithEmail")
    @ResponseWrapper(localName = "isUserWithEmailResponse", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.IsUserWithEmailResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.sigeceunasecurityws.controller.UserDto isUserWithEmail(

        @WebParam(name = "email", targetNamespace = "")
        java.lang.String email
    );

    @WebMethod
    @Action(input = "http://controller.sigeceunasecurityws.una.ac.cr/UserController/saveUserRsRequest", output = "http://controller.sigeceunasecurityws.una.ac.cr/UserController/saveUserRsResponse")
    @RequestWrapper(localName = "saveUserRs", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.SaveUserRs")
    @ResponseWrapper(localName = "saveUserRsResponse", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.SaveUserRsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.sigeceunasecurityws.controller.Response saveUserRs(

        @WebParam(name = "arg0", targetNamespace = "")
        cr.ac.una.sigeceunasecurityws.controller.UserDto arg0
    );

    @WebMethod
    @Action(input = "http://controller.sigeceunasecurityws.una.ac.cr/UserController/getUsersRequest", output = "http://controller.sigeceunasecurityws.una.ac.cr/UserController/getUsersResponse")
    @RequestWrapper(localName = "getUsers", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.GetUsers")
    @ResponseWrapper(localName = "getUsersResponse", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.GetUsersResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<cr.ac.una.sigeceunasecurityws.controller.UserDto> getUsers()
;

    @WebMethod
    @Action(input = "http://controller.sigeceunasecurityws.una.ac.cr/UserController/validateUserRsRequest", output = "http://controller.sigeceunasecurityws.una.ac.cr/UserController/validateUserRsResponse")
    @RequestWrapper(localName = "validateUserRs", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.ValidateUserRs")
    @ResponseWrapper(localName = "validateUserRsResponse", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.ValidateUserRsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.sigeceunasecurityws.controller.Response validateUserRs(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://controller.sigeceunasecurityws.una.ac.cr/UserController/validateUserWithTempPasswordRequest", output = "http://controller.sigeceunasecurityws.una.ac.cr/UserController/validateUserWithTempPasswordResponse")
    @RequestWrapper(localName = "validateUserWithTempPassword", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.ValidateUserWithTempPassword")
    @ResponseWrapper(localName = "validateUserWithTempPasswordResponse", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.ValidateUserWithTempPasswordResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.sigeceunasecurityws.controller.UserDto validateUserWithTempPassword(

        @WebParam(name = "identification", targetNamespace = "")
        java.lang.String identification,
        @WebParam(name = "tempPassword", targetNamespace = "")
        java.lang.String tempPassword
    );

    @WebMethod
    @Action(input = "http://controller.sigeceunasecurityws.una.ac.cr/UserController/deleteUserByIDRequest", output = "http://controller.sigeceunasecurityws.una.ac.cr/UserController/deleteUserByIDResponse")
    @RequestWrapper(localName = "deleteUserByID", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.DeleteUserByID")
    @ResponseWrapper(localName = "deleteUserByIDResponse", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.DeleteUserByIDResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Boolean deleteUserByID(

        @WebParam(name = "ID", targetNamespace = "")
        java.lang.Long id
    );

    @WebMethod
    @Action(input = "http://controller.sigeceunasecurityws.una.ac.cr/UserController/saveUserRequest", output = "http://controller.sigeceunasecurityws.una.ac.cr/UserController/saveUserResponse")
    @RequestWrapper(localName = "saveUser", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.SaveUser")
    @ResponseWrapper(localName = "saveUserResponse", targetNamespace = "http://controller.sigeceunasecurityws.una.ac.cr/", className = "cr.ac.una.sigeceunasecurityws.controller.SaveUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.sigeceunasecurityws.controller.UserDto saveUser(

        @WebParam(name = "userToRegister", targetNamespace = "")
        cr.ac.una.sigeceunasecurityws.controller.UserDto userToRegister
    );
}
